# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_of_pages', models.IntegerField()),
                ('cover', models.CharField(blank=True, max_length=250, null=True)),
                ('has_articles', models.BooleanField()),
                ('journal_name', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_cover', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_thumb', models.CharField(blank=True, max_length=250, null=True)),
                ('release_date', models.DateField()),
                ('thumb', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('cover', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_issue', models.IntegerField()),
                ('mobile_cover', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile_thumb', models.CharField(blank=True, max_length=250, null=True)),
                ('thumb', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme2Journal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Journal')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='TopJournal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reader_url', models.CharField(max_length=250)),
                ('journal_name_en', models.CharField(blank=True, max_length=250, null=True)),
                ('journal_name', models.CharField(max_length=250)),
                ('issue_name', models.CharField(max_length=250)),
                ('journal_id', models.IntegerField()),
                ('issue_id', models.IntegerField()),
                ('cover_url', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Journal'),
        ),
    ]
