# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='uid',
        ),
    ]
