# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_theme_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('text_continue', models.TextField()),
                ('small_image_square', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('short_text', models.TextField()),
                ('reader_url', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('small_image_portrait', models.CharField(max_length=250)),
                ('small_image', models.CharField(max_length=250)),
                ('issue_id', models.IntegerField()),
                ('issue', models.CharField(max_length=250)),
                ('journal', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
