# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_toparticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_url', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('small_image', models.CharField(max_length=250)),
                ('square_image', models.CharField(max_length=250)),
                ('short_text', models.CharField(max_length=250)),
                ('page', models.CharField(max_length=250)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Issue')),
            ],
        ),
        migrations.AlterField(
            model_name='theme2journal',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Journal'),
        ),
        migrations.AlterField(
            model_name='theme2journal',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Theme'),
        ),
    ]
