# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180920_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
